"""
(A1) for Project 29: a proximal bundle method on the Lagrangian dual obtained by
dualising the *representer identity* of the SVM dual.

    (D')  min_{alpha in D, w}  1/2||w||^2 - 1^T alpha
          s.t.                 w = sum_i alpha_i y_i phi(x_i)          <-- dualised
          D = { 0 <= alpha <= C ,  y^T alpha = 0 }

    phi(lambda) = -1/2||lambda||^2 + min_{alpha in D} c(lambda)^T alpha
    c_i(lambda) = -( 1 + y_i <lambda, phi(x_i)> )

phi is finite everywhere (D is a non-empty compact polytope), concave, and is
   (smooth, known in closed form)  +  (concave polyhedral) ,
so the bundle model linearises ONLY the polyhedral part and keeps the quadratic
exact -- a "generalized"/structured bundle in the sense of Frangioni.

lambda lives in the RKHS; by a representer argument we may write
lambda = sum_j beta_j phi(x_j), so <lambda, phi(x_i)> = (K beta)_i and
||lambda||^2 = beta^T K beta.  The stabilising term is the RKHS norm
||lambda - lambda_bar||^2 = (beta - beta_bar)^T K (beta - beta_bar).

MASTER PROBLEM.  With cuts generated by alpha^1..alpha^J in D, write
a_j = 1^T alpha^j and b_j = Y alpha^j.  The master and its dual are

  max_beta  -1/2||beta||_K^2 + min_j { -a_j - beta^T K b_j }
                             - 1/(2t) ||beta - beta_bar||_K^2
  =  min_{theta in simplex}  1/(2rho) ||beta_bar/t - B theta||_K^2 - a^T theta

with rho = 1 + 1/t, and then beta_new = (beta_bar/t - B theta)/rho.  Only the
J x J matrix G = B^T K B and the vector p = B^T K beta_bar are needed, both
maintained incrementally, so the master costs O(J^2) plus one kernel product
per new cut.  It is handed to an off-the-shelf QP solver, which the project
statement explicitly allows.

Setting theta as the master multipliers, alpha_hat = sum_j theta_j alpha^j lies
in D and is the primal solution: the method is exactly Dantzig-Wolfe
decomposition of the SVM dual, with the continuous knapsack as pricing problem.
"""
import numpy as np
import cvxpy as cp

from knapsack_oracle import continuous_knapsack


# --------------------------------------------------------------------------- #
# kernels
# --------------------------------------------------------------------------- #
def kernel_matrix(X, Z=None, kind="linear", gamma=None, degree=3, coef0=1.0):
    Z = X if Z is None else Z
    if kind == "linear":
        return X @ Z.T
    if kind == "rbf":
        gamma = 1.0 / X.shape[1] if gamma is None else gamma
        d2 = (X * X).sum(1)[:, None] + (Z * Z).sum(1)[None, :] - 2.0 * X @ Z.T
        return np.exp(-gamma * np.maximum(d2, 0.0))
    if kind == "poly":
        gamma = 1.0 / X.shape[1] if gamma is None else gamma
        return (gamma * (X @ Z.T) + coef0) ** degree
    raise ValueError(f"unknown kernel {kind!r}")


# --------------------------------------------------------------------------- #
# the oracle:  phi(beta), the knapsack solution alpha, and the multiplier theta
# --------------------------------------------------------------------------- #
class DualOracle:
    """Evaluates phi.  One kernel product + one O(m log m) sort per call."""

    def __init__(self, K, y, C):
        self.K, self.y, self.C = K, y, C
        self.n_calls = 0

    def __call__(self, beta, Kbeta=None):
        self.n_calls += 1
        Kb = self.K @ beta if Kbeta is None else Kbeta
        alpha, lin, theta, n_tied = continuous_knapsack(-(1.0 + self.y * Kb), self.y, self.C)
        return -0.5 * beta @ Kb + lin, alpha, theta, n_tied


# --------------------------------------------------------------------------- #
# the master problem
# --------------------------------------------------------------------------- #
def _solve_master(G, a_lin, p, t, rho):
    """min_{theta in simplex} 1/(2rho)(theta'G theta - 2/t p'theta) - a'theta."""
    J = G.shape[0]
    if J == 1:
        return np.ones(1)
    Gs = 0.5 * (G + G.T)
    Gs = Gs + 1e-11 * np.trace(Gs) / max(J, 1) * np.eye(J)
    th = cp.Variable(J, nonneg=True)
    obj = (0.5 / rho) * (cp.quad_form(th, cp.psd_wrap(Gs)) - (2.0 / t) * (p @ th)) - a_lin @ th
    prob = cp.Problem(cp.Minimize(obj), [cp.sum(th) == 1])
    for slv in (cp.CLARABEL, cp.OSQP, cp.SCS):
        try:
            prob.solve(solver=slv)
            if th.value is not None and np.all(np.isfinite(th.value)):
                break
        except Exception:
            continue
    v = np.clip(np.asarray(th.value, dtype=float).ravel(), 0.0, None)
    s = v.sum()
    return v / s if s > 0 else np.ones(J) / J


# --------------------------------------------------------------------------- #
# the bundle method
# --------------------------------------------------------------------------- #
def bundle_solve(K, y, C, tol=1e-8, max_iter=500, t0=1.0, t_min=1e-3, t_max=1e4,
                 kappa=0.1, max_bundle=None, beta0=None, cuts0=None, verbose=False):
    """Maximise phi over beta.  Returns alpha*, b, the certified gap and a history.

    cuts0 : optional list of alpha vectors in D used to seed the bundle
            (the One-vs-Rest transfer mechanism, see transfer_cuts()).
    beta0 : optional warm start for the multiplier.

    NOTE on max_bundle.  The oracle returns (essentially) vertices of D, i.e.
    0/C vectors, and the master writes alpha_hat as a convex combination of
    them.  Components of alpha* that are at a bound need one vertex; every
    FREE support vector (0 < alpha_i* < C) has to be produced by mixing
    vertices that disagree on i.  The number of cuts the method needs is
    therefore governed by the number of free support vectors, and truncating
    the bundle below that number makes the gap stall (classic Dantzig-Wolfe
    tailing-off).  The default leaves room for m/2 cuts.
    """
    m = K.shape[0]
    if max_bundle is None:
        max_bundle = int(max(50, min(m, 250)))
    oracle = DualOracle(K, y, C)
    t = float(t0)

    beta_bar = np.zeros(m) if beta0 is None else np.asarray(beta0, dtype=float).copy()
    Kbb = K @ beta_bar
    f_bar, alpha_bar, theta_bar, _ = oracle(beta_bar, Kbeta=Kbb)
    best_lb, best_alpha, best_theta = f_bar, alpha_bar, theta_bar

    # bundle: columns b_j = Y alpha^j, with K b_j cached
    seeds = [np.asarray(a, dtype=float) for a in (cuts0 or [])] + [alpha_bar]
    A = np.array(seeds)                                   # J x m
    B = (A * y).T                                         # m x J
    KB = K @ B                                            # m x J  (J kernel products)
    G = B.T @ KB                                          # J x J
    a_lin = A.sum(1)

    history, gap, ub, alpha_hat = [], np.inf, np.inf, alpha_bar
    for it in range(1, max_iter + 1):
        rho = 1.0 + 1.0 / t
        p = KB.T @ beta_bar
        th = _solve_master(G, a_lin, p, t, rho)

        alpha_hat = A.T @ th                              # aggregate primal, in D
        Bth, KBth = B @ th, KB @ th
        beta_new = (beta_bar / t - Bth) / rho
        Kbn = (Kbb / t - KBth) / rho                      # K beta_new, no new matvec

        ub = 0.5 * (Bth @ KBth) - alpha_hat.sum()         # restricted (D) >= v(D)
        f_new, alpha_new, theta_new, n_tied = oracle(beta_new, Kbeta=Kbn)
        if f_new > best_lb:
            best_lb, best_alpha, best_theta = f_new, alpha_new, theta_new
        gap = ub - best_lb
        history.append(dict(it=it, lb=best_lb, ub=ub, gap=gap, cuts=A.shape[0],
                            tied=n_tied, t=t, oracle_calls=oracle.n_calls))
        if verbose and (it <= 5 or it % 25 == 0):
            print(f"    it {it:4d} lb={best_lb: .10f} ub={ub: .10f} gap={gap:.2e} "
                  f"J={A.shape[0]} t={t:.3g}")
        if gap <= tol * max(1.0, abs(ub)):
            break

        # model value at beta_new: predicted increase drives the serious/null test
        model = -0.5 * beta_new @ Kbn + np.min(-a_lin - KB.T @ beta_new)
        if f_new >= f_bar + kappa * (model - f_bar):      # serious step
            beta_bar, Kbb, f_bar = beta_new, Kbn, f_new
            t = min(t * 1.5, t_max)
        else:                                             # null step
            t = max(t * 0.6, t_min)

        # append the new cut (one kernel product), then aggregate if too large
        b_new = y * alpha_new
        Kb_new = K @ b_new
        A = np.vstack([A, alpha_new])
        B = np.column_stack([B, b_new])
        KB = np.column_stack([KB, Kb_new])
        col = B.T @ Kb_new
        G = np.block([[G, col[:-1, None]], [col[None, :-1], col[-1:][None, :]]])
        a_lin = np.append(a_lin, alpha_new.sum())

        if A.shape[0] > max_bundle:
            keep = list(range(A.shape[0] - (max_bundle - 1), A.shape[0]))
            A = np.vstack([alpha_hat, A[keep]])            # keep the aggregate cut
            B = np.column_stack([Bth, B[:, keep]])
            KB = np.column_stack([KBth, KB[:, keep]])
            G = B.T @ KB
            a_lin = A.sum(1)

    return dict(alpha=alpha_hat, alpha_oracle=best_alpha, beta=beta_new,
                b=-best_theta, lb=best_lb, ub=ub, gap=gap, iters=len(history),
                oracle_calls=oracle.n_calls, history=history, bundle=list(A))


# --------------------------------------------------------------------------- #
# One-vs-Rest transfer
# --------------------------------------------------------------------------- #
def transfer_cuts(alphas, y_old_list, y_new, C):
    """
    Turn cuts collected for other One-vs-Rest classes into valid cuts for the
    current one.  Any point of D^l gives a valid cut for class l, and the D^k
    differ ONLY through the equality y^T alpha = 0.  Writing P_k / P_l for the
    two positive blocks and R for the rest, a point of D^k satisfies
        alpha(P_k) = alpha(P_l) + alpha(R),
    so  y^l . alpha = -2 alpha(R):  the imbalance is known in closed form and is
    repaired by pushing mass onto P_l (and, if that saturates, trimming R).
    This keeps the support pattern of the transferred cut, which the naive
    "re-solve a knapsack" repair destroys.  Cost: O(m) per cut, no oracle call.
    """
    out = []
    for a, y_old in zip(alphas, y_old_list):
        a = np.asarray(a, dtype=float).copy()
        Pl = y_new > 0
        need = -(y_new @ a)                       # move this much onto P_l
        if abs(need) < 1e-12:
            out.append(a)
            continue
        if need > 0:
            room = C - a[Pl]
            take = min(need, room.sum())
            if room.sum() > 1e-12:
                a[Pl] += room * (take / room.sum())
            need -= take
            if need > 1e-12:                      # still unbalanced: trim negatives
                neg = y_new < 0
                have = a[neg]
                if have.sum() > 1e-12:
                    a[neg] -= have * (min(need, have.sum()) / have.sum())
        else:
            have = a[Pl]
            if have.sum() > 1e-12:
                a[Pl] -= have * (min(-need, have.sum()) / have.sum())
        a = np.clip(a, 0.0, C)
        if abs(y_new @ a) < 1e-8:
            out.append(a)
    return out
